### login route
### signup
POST http://localhost:5050/api/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Abdullah",
  "email": "abdullah@email.com",
  "password": "123",
  "passwordConfirmation": "123"
}

### login with valid credentials
POST http://localhost:5050/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "abdullah@email.com",
  "password": "123"
}

### surveys route
### add survey
POST http://localhost:5050/api/surveys HTTP/1.1
Content-Type: application/json

{
  "question": "Do you like dogs?",
  "answers": [
    {
      "image": "image-none",
      "answer": "Yes"
    }
  ]
}
